<!DOCTYPE html>
<html>
  <head>
       <title>events</title>
       <link rel="icon" href="img/date.png">

  </head>

  <body bgcolor="black" style="color: white;">
      <center>
        <h1>upcoming event📅</h1>
        <p>Don't miss any of your events.stay updated</p>
      </center>

      <hr>
    </p>
    Lorem ipsum dolor sit amet, consectetur adipisicing elit. Perspiciatis, aut veritatis? Architecto aspernatur repellat culpa, iusto quis incidunt ad necessitatibus nam minima hic repudiandae fugiat voluptatem debitis illo sequi nobis magnam vitae obcaecati totam distinctio assumenda reprehenderit inventore consectetur. Maxime, ullam nulla voluptates voluptatum enim optio quas vero quasi non magnam necessitatibus velit adipisci blanditiis expedita, magni voluptas odit eos. Est beatae vero, et iusto laudantium voluptates quam labore rerum ipsa, soluta deleniti amet exercitationem placeat reprehenderit sequi voluptate accusamus culpa eius. Mollitia consequatur, delectus possimus doloribus blanditiis adipisci, accusamus obcaecati praesentium nemo molestiae minus suscipit sit explicabo distinctio quasi!

      </p>
<center>
      <img src="img/event1.png">
     <h1>photo gallery</h1> 
     <h2>free entery /free food/ pets are not allowe<d/h2>
    <p>
        Lorem ipsum, dolor sit amet consectetur adipisicing elit. Ipsa nihil aut ut aperiam quaerat. Nostrum iusto ex incidunt harum aliquam, consequuntur eius cupiditate consequatur nisi? Error atque minima dolores at perspiciatis inventore nulla totam rem! Omnis ad temporibus magni explicabo, optio atque! Aperiam molestiae facilis quas sapiente, libero mollitia cupiditate.
    </p>
    </center>


<center>
    <img src="img/event2.png">
,<h1>
    <a href="https://www.myntra.com/">fassion store</a>
</h1>
<h2>free entery /free food/ pets are not allowe<d/h2>
    <p>
        Lorem ipsum, dolor sit amet consectetur adipisicing elit. Ipsa nihil aut ut aperiam quaerat. Nostrum iusto ex incidunt harum aliquam, consequuntur eius cupiditate consequatur nisi? Error atque minima dolores at perspiciatis inventore nulla totam rem! Omnis ad temporibus magni explicabo, optio atque! Aperiam molestiae facilis quas sapiente, libero mollitia cupiditate.
    </p>
</center>
<hr>
<center>
<h1>contact</h1>
<h2>+9360255988/gokg270@gmail.com</h2>
<h3>address : palavakkam chennai.41</h3>
</center>







  </body
